{
 "title": "Finance Polyus",
 "description": "ok",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Общее количество добытого золота поквартально",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "koz" } },
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", value \nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'QUARTERLY' ) AND ( name = 'Total gold produced2' )\nUNION ALL\nSELECT date as \"time\", value/2\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'SEMI-ANNUAL' ) AND ( name = 'Total gold produced2' )\nORDER BY time ASC LIMIT 1000"
    },
    {
     "rawSql": "SELECT date as \"time\", value \nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'ANNUAL' ) AND ( name = 'Total gold produced2' )"
    }
   ]
  },
  {
   "title": "Общее количество добытого золота поквартально",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "koz" } },
   "targets": [
    {
     "rawSql": "select * from (SELECT table, date as \"time\", value \nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table != 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'QUARTERLY' ) AND ( name like 'Total refined gold output%' )\nUNION ALL\nSELECT table, date as \"time\", value/2\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table != 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'SEMI-ANNUAL' ) AND ( name like 'Total refined gold output%' )\n) ORDER BY time ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Общее количество добытой руды поквартально и объем горной массы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", value \nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'QUARTERLY' ) AND ( name = 'Ore mined' )\nUNION ALL\nSELECT date as \"time\", value/2\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'SEMI-ANNUAL' ) AND ( name = 'Ore mined' )\nORDER BY time ASC LIMIT 1000"
    },
    {
     "rawSql": "SELECT date as \"time\", value \nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'QUARTERLY' ) AND ( name = 'Total rock moved' )\nUNION ALL\nSELECT date as \"time\", value/2\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'SEMI-ANNUAL' ) AND ( name = 'Total rock moved' )\nORDER BY time ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Общее количество добытой руды поквартально",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "rawSql": "select * from (SELECT table, date as \"time\", value \nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table != 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'QUARTERLY' ) AND ( name = 'Ore mined' )\nUNION ALL\nSELECT table, date as \"time\", value/2\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table != 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'SEMI-ANNUAL' ) AND ( name = 'Ore mined' ))\nORDER BY time ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Среднее содержание золота в добытой руде, Коэффициент извлечения и Коэффициент вскрыши",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "g/t" } },
   "targets": [
    {
     "rawSql": "select * from (SELECT date as \"time\", value as \"g/t\" \nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'QUARTERLY' ) AND ( name = 'Average grade in ore mined' )\nUNION ALL\nSELECT date as \"time\", value\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'SEMI-ANNUAL' ) AND ( name = 'Average grade in ore mined' )\n) ORDER BY time ASC LIMIT 1000"
    },
    {
     "rawSql": "select * from (SELECT date as \"time\", value as \"%\"\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'QUARTERLY' ) AND ( name = 'Recovery' )\nUNION ALL\nSELECT date as \"time\", value\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'SEMI-ANNUAL' ) AND ( name = 'Recovery' )\n) ORDER BY time ASC LIMIT 1000"
    },
    {
     "rawSql": "select * from (SELECT date as \"time\", value as \"m3/t\"\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'QUARTERLY' ) AND ( name = 'Stripping ratio' )\nUNION ALL\nSELECT date as \"time\", value\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table = 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'SEMI-ANNUAL' ) AND ( name = 'Stripping ratio' )\n) ORDER BY time ASC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Общее количество перемещенных камней",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "select * from (SELECT table, date as \"time\", value \nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table != 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'QUARTERLY' ) AND ( name = 'Total rock moved' )\nUNION ALL\nSELECT table, date as \"time\", value/2\nFROM \"default\".\"databook_polyus\" FINAL\nWHERE ( time >= $__fromTime AND time <= $__toTime ) AND ( table != 'CONSOLIDATED OPERATING RESULTS' ) AND ( data = 'SEMI-ANNUAL' ) AND ( name = 'Total rock moved' ))\nORDER BY time ASC LIMIT 1000"
    }
   ]
  }
 ]
}